module Seed
	def self.staff(editions, activities)
		User.create!(staff_list(editions, activities).each { |s| s[:email].sub!(/<at>/, '@')})
	end

	def self.staff_list(editions, activities)
		[
			{
				email: 'andreccdr<at>gmail.com',
				password: '123456789',
				first_name: "André",
				last_name: "Santos",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('André Santos').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/asantos.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Presidente",
				activities: [],
				editions: [editions[0]],
				twitter_account: "https://twitter.com/62Gerente",
				github_account: "https://github.com/62Gerente",
				facebook_account: "",
				linked_in_account: "http://pt.linkedin.com/in/62gerente",
				location: 'Braga'
			},
			{
				email: 'mcpinto98<at>gmail.com',
				password: '123456789',
				first_name: "Miguel",
				last_name: "Pinto",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('Miguel Pinto').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/mpinto.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Vice Presidente",
				activities: [],
				editions: [editions[0]],
				twitter_account: "",
				github_account: "https://github.com/miguelpinto98",
				facebook_account: "https://www.facebook.com/mcpinto98",
				linked_in_account: "https://pt.linkedin.com/in/miguelpinto98",
				location: 'Braga'
			},
			{
				email: 'pedroduarte870<at>gmail.com',
				password: '123456789',
				first_name: "Pedro",
				last_name: "Duarte",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('Pedro Duarte').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/pduarte.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Vice Presidente",
				activities: [],
				editions: [editions[0]],
				twitter_account: "https://twitter.com/pedroduarte870",
				github_account: "https://github.com/pedroduarte870",
				facebook_account: "https://www.facebook.com/pedrodpduarte870",
				linked_in_account: "",
				location: 'Braga'
			},
			{
				email: 'maiarib<at>gmail.com',
				password: '123456789',
				first_name: "Pedro",
				last_name: "Maia",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('Pedro Maia').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/pmaia.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Tesoureiro",
				activities: [],
				editions: [editions[0]],
				twitter_account: "",
				github_account: "https://github.com/PedroMaia",
				facebook_account: "",
				linked_in_account: "https://pt.linkedin.com/in/maiarib",
				location: 'Braga'
			},
			{
				email: 'bpatrcia<at>gmail.com',
				password: '123456789',
				first_name: "Patrícia",
				last_name: "Barros",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('Patrícia Barros').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/pbarros.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Secretária",
				activities: [],
				editions: [editions[0]],
				twitter_account: "",
				github_account: "https://github.com/7patricia",
				facebook_account: "",
				linked_in_account: "https://pt.linkedin.com/in/7patricia",
				location: 'Braga'
			},
			{
				email: 'fjrib.mendes<at>gmail.com',
				password: '123456789',
				first_name: "Fernando",
				last_name: "Mendes",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('Fernando Mendes').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/fmendes.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Diretor do Centro de Apoio ao Open Source",
				activities: [],
				editions: [editions[0]],
				twitter_account: "https://twitter.com/fribmendes",
				github_account: "https://github.com/frmendes",
				facebook_account: "",
				linked_in_account: "https://pt.linkedin.com/in/fribmendes",
				location: 'Braga'
			},
			{
				email: 'martinhoaragao<at>gmail.com',
				password: '123456789',
				first_name: "Martinho",
				last_name: "Aragão",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('Martinho Aragão ').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/maragao.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Vice Diretor do Centro de Apoio ao Open Source",
				activities: [],
				editions: [editions[0]],
				twitter_account: "https://twitter.com/martinhoaragao",
				github_account: "https://github.com/martinhoaragao",
				facebook_account: "",
				linked_in_account: "https://pt.linkedin.com/in/martinhoaragao",
				location: 'Braga'
			},
			{
				email: 'fntneves<at>gmail.com',
				password: '123456789',
				first_name: "Francisco",
				last_name: "Neves",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('Francisco Neves').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/fneves.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Diretor do Departamento Pedagógico",
				activities: [],
				editions: [editions[0]],
				twitter_account: "https://twitter.com/fntneves",
				github_account: "https://github.com/fntneves",
				facebook_account: "",
				linked_in_account: "https://www.linkedin.com/in/fntneves",
				location: 'Braga'
			},
			{
				email: 'mrfabiogomes<at>gmail.com',
				password: '123456789',
				first_name: "Fábio",
				last_name: "Gomes",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('Fábio Gomes').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/fgomes.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Vice Diretor do Departamento Pedagógico",
				activities: [],
				editions: [editions[0]],
				twitter_account: "https://twitter.com/SHIFTBASIC",
				github_account: "https://github.com/MrFabio",
				facebook_account: "",
				linked_in_account: "https://www.linkedin.com/profile/view?id=353827731",
				location: 'Braga'
			},
			{
				email: 'tiagocunha<at>seium.org',
				password: '123456789',
				first_name: "Tiago",
				last_name: "Cunha",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('Tiago Cunha').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/tcunha.png"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Diretor do Departamento Recreativo",
				activities: [],
				editions: [editions[0]],
				twitter_account: "",
				github_account: "",
				facebook_account: "https://www.facebook.com/Apocalipse.113",
				linked_in_account: "",
				location: 'Braga'
			},
			{
				email: 'pmiguelf15<at>gmail.com',
				password: '123456789',
				first_name: "Pedro",
				last_name: "Faria",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('Pedro Faria').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/pfaria.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Vice Diretor do Departamento Recreativo",
				activities: [],
				editions: [editions[0]],
				twitter_account: "",
				github_account: "",
				facebook_account: "https://www.facebook.com/NoventaESeis",
				linked_in_account: "",
				location: 'Braga'
			},
			{
				email: 'gilgoncalves<at>seium.org',
				password: '123456789',
				first_name: "Gil",
				last_name: "Gonçalves",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('Gil Gonçalves').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/ggoncalves.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Vice Diretor do Departamento Recreativo",
				activities: [],
				editions: [editions[0]],
				twitter_account: "",
				github_account: "",
				facebook_account: "https://www.facebook.com/gil.goncalves.161",
				linked_in_account: "",
				location: 'Braga'
			},
			{
				email: 'filipecosta.90<at>gmail.com',
				password: '123456789',
				first_name: "Filipe",
				last_name: "Oliveira",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('Filipe Oliveira').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/foliveira.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Diretor do Departamento de Comunicação e Imagem",
				activities: [],
				editions: [editions[0]],
				twitter_account: "",
				github_account: "",
				facebook_account: "https://www.facebook.com/filipecosta.90",
				linked_in_account: "",
				location: 'Braga'
			},
			{
				email: '63msim<at>gmail.com',
				password: '123456789',
				first_name: "Mariana",
				last_name: "Medeiros",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('Mariana Medeiros').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/mmedeiros.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Vice Diretora do Departamento de Comunicação",
				activities: [],
				editions: [editions[0]],
				twitter_account: "",
				github_account: "https://github.com/Mariana63",
				facebook_account: "https://www.facebook.com/mim063",
				linked_in_account: "https://pt.linkedin.com/in/mariana63medeiros",
				location: 'Braga'
			},
			{
				email: 'schroeder.jorge<at>gmail.com',
				password: '123456789',
				first_name: "Jorge",
				last_name: "Simão",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('Jorge Simão').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/jsimao.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Vice Diretor do Departamento de Imagem",
				activities: [],
				editions: [editions[0]],
				twitter_account: "",
				github_account: "",
				facebook_account: "",
				linked_in_account: "http://pt.linkedin.com/in/jorgepedrosimao",
				location: 'Braga'
			},
			{
				email: 'prsousa34<at>gmail.com',
				password: '123456789',
				first_name: "Paulo",
				last_name: "Sousa",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('Paulo Sousa').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/psousa.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Diretor do Dep. de Relações Externas e Parcerias",
				activities: [],
				editions: [editions[0]],
				twitter_account: "",
				github_account: "https://github.com/prsousa",
				facebook_account: "https://www.facebook.com/34chronos",
				linked_in_account: "",
				location: 'Braga'
			},
			{
				email: 'santos.mario125<at>gmail.com',
				password: '123456789',
				first_name: "Mário",
				last_name: "Santos",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('Mário Santos').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/msantos.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Vice Diretor do Dep. de Relações Externas e Parcerias",
				activities: [],
				editions: [editions[0]],
				twitter_account: "https://twitter.com/MarioSantos125",
				github_account: "https://github.com/Galay125",
				facebook_account: "",
				linked_in_account: "https://lnkd.in/A7mvHm",
				location: 'Braga'
			},
			{
				email: 'smcp92<at>gmail.com',
				password: '123456789',
				first_name: "Serafim",
				last_name: "Pinto",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('Serafim Pinto').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/spinto.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Vogal",
				activities: [],
				editions: [editions[0]],
				twitter_account: "",
				github_account: "https://github.com/serafimpinto",
				facebook_account: "",
				linked_in_account: "http://pt.linkedin.com/in/serafimpinto",
				location: 'Braga'
			},
			{
				email: 'pedrosfdcarneiro<at>gmail.com',
				password: '123456789',
				first_name: "Pedro",
				last_name: "Carneiro",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('Pedro Carneiro').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/pcarneiro.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Vogal",
				activities: [],
				editions: [editions[0]],
				twitter_account: "https://twitter.com/pedrosfdc",
				github_account: "https://github.com/pedrosfdcarneiro",
				facebook_account: "https://www.facebook.com/pedrosfdcarneiro",
				linked_in_account: "",
				location: 'Braga'
			},
			{
				email: 'sandraferreira<at>seium.org',
				password: '123456789',
				first_name: "Sandra",
				last_name: "Ferreira",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('Sandra Ferreira').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/sferreira.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Vogal",
				activities: [],
				editions: [editions[0]],
				twitter_account: "",
				github_account: "",
				facebook_account: "https://www.facebook.com/sandra.ferreira.96742",
				linked_in_account: "",
				location: 'Braga'
			},
			{
				email: 'maleite.cbc<at>gmail.com',
				password: '123456789',
				first_name: "Mário",
				last_name: "Leite",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('Mário Leite').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/mleite.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Vogal",
				activities: [],
				editions: [editions[0]],
				twitter_account: "",
				github_account: "https://github.com/maleite",
				facebook_account: "https://www.facebook.com/mario.leite.80",
				linked_in_account: "https://www.linkedin.com/in/marioleite80",
				location: 'Braga'
			},
			{
				email: 'mail<at>danielcarvalho.pt',
				password: '123456789',
				first_name: "Daniel",
				last_name: "Carvalho",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('Daniel Carvalho').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/dcarvalho.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Assembleia Geral",
				activities: [],
				editions: [editions[0]],
				twitter_account: "https://twitter.com/dapcarvalho/",
				github_account: "https://github.com/Insatisfeito",
				facebook_account: "",
				linked_in_account: "https://pt.linkedin.com/in/dapcarvalho/",
				location: 'Braga'
			},
			{
				email: '28.ricardobranco<at>gmail.com',
				password: '123456789',
				first_name: "Ricardo",
				last_name: "Branco",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('Ricardo Branco').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/rbranco.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Assembleia Geral",
				activities: [],
				editions: [editions[0]],
				twitter_account: "",
				github_account: "https://github.com/ricardobranco",
				facebook_account: "https://www.facebook.com/ricardobranco28",
				linked_in_account: "",
				location: 'Braga'
			},
			{
				email: '53.andre.pimenta<at>gmail.com',
				password: '123456789',
				first_name: "André",
				last_name: "Pimenta",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('André Pimenta').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/apimenta.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Conselho Fiscal",
				activities: [],
				editions: [editions[0]],
				twitter_account: "",
				github_account: "",
				facebook_account: "https://www.facebook.com/pimenta53",
				linked_in_account: "",
				location: 'Braga'
			},
			{
				email: 'pmcleite<at>gmail.com',
				password: '123456789',
				first_name: "Pedro",
				last_name: "Leite",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('Pedro Leite').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/pleite.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Conselho Fiscal",
				activities: [],
				editions: [editions[0]],
				twitter_account: "https://twitter.com/pmcleite",
				github_account: "https://github.com/pmcleite",
				facebook_account: "",
				linked_in_account: "https://www.linkedin.com/in/pmcleite",
				location: 'Braga'
			},
			{
				email: 'rui96pedro<at>gmail.com',
				password: '123456789',
				first_name: "Rui",
				last_name: "Oliveira",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('Rui Oliveira').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/roliveira.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Membro",
				activities: [],
				editions: [editions[0]],
				twitter_account: "",
				github_account: "https://bitbucket.org/ruioliveiras",
				facebook_account: "https://www.facebook.com/rui.oliveiras",
				linked_in_account: "",
				location: 'Braga'
			},
			{
				email: 'ajoao_19<at>hotmail.com',
				password: '123456789',
				first_name: "João",
				last_name: "Costa",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('João Costa').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/jcosta.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Membro",
				activities: [],
				editions: [editions[0]],
				twitter_account: "",
				github_account: "https://github.com/joaofcosta",
				facebook_account: "https://www.facebook.com/arnaldo.asturias.9",
				linked_in_account: "",
				location: 'Braga'
			},
			{
				email: 'pcardoso.lei<at>gmail.com',
				password: '123456789',
				first_name: "Paulo",
				last_name: "Cardoso",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('Paulo Cardoso').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/pcardoso.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Membro",
				activities: [],
				editions: [editions[0]],
				twitter_account: "https://twitter.com/HeadlessHeader",
				github_account: "https://github.com/pcardosolei",
				facebook_account: "",
				linked_in_account: "https://pt.linkedin.com/in/pcardosolei/",
				location: 'Braga'
			},
			{
				email: 'frize_91<at>hotmail.com',
				password: '123456789',
				first_name: "Joana",
				last_name: "Arantes",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('Joana Arantes').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/jarantes.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Membro",
				activities: [],
				editions: [editions[0]],
				twitter_account: "",
				github_account: "https://github.com/joanaarantes",
				facebook_account: "https://www.facebook.com/joana.arantes.10",
				linked_in_account: "",
				location: 'Braga'
			},
			{
				email: 'sukinha_mendes<at>hotmail.com',
				password: '123456789',
				first_name: "Susana",
				last_name: "Mendes",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('Susana Mendes').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/smendes.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Membro",
				activities: [],
				editions: [editions[0]],
				twitter_account: "https://twitter.com/Su__Mendes",
				github_account: "",
				facebook_account: "",
				linked_in_account: "https://www.linkedin.com/pub/susana-mendes/43/8b8/906",
				location: 'Braga'
			},
			{
				email: 'chalkos<at>chalkos.net',
				password: '123456789',
				first_name: "Bruno",
				last_name: "Ferreira",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('Bruno Ferreira').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/bferreira.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Membro",
				activities: [],
				editions: [editions[0]],
				twitter_account: "https://twitter.com/chalkos",
				github_account: "https://github.com/chalkos",
				facebook_account: "",
				linked_in_account: "https://pt.linkedin.com/in/chalkos",
				location: 'Braga'
			},
			{
				email: 'psac92<at>hotmail.com',
				password: '123456789',
				first_name: "Pedro",
				last_name: "Costa",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('Pedro Costa').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/pcosta.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Membro",
				activities: [],
				editions: [editions[0]],
				twitter_account: "https://twitter.com/santosk20",
				github_account: "https://github.com/santosk20",
				facebook_account: "https://www.facebook.com/pedrocosta92",
				linked_in_account: "",
				location: 'Braga'
			},
			{
				email: 'demosbb<at>gmail.com',
				password: '123456789',
				first_name: "Diana",
				last_name: "Lemos",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('Diana Lemos').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/dlemos.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Membro",
				activities: [],
				editions: [editions[0]],
				twitter_account: "",
				github_account: "https://github.com/dianalemos",
				facebook_account: "https://www.facebook.com/dianaguimaraes57",
				linked_in_account: "https://www.linkedin.com/profile/view?id=227209565&trk=nav_responsive_tab_profile",
				location: 'Braga'
			},
			{
				email: 'pedro_miguelsilva<at>outlook.com',
				password: '123456789',
				first_name: "Pedro",
				last_name: "Silva",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('Pedro Silva').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/psilva.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Membro",
				activities: [],
				editions: [editions[0]],
				twitter_account: "",
				github_account: "https://github.com/pedroSilva4",
				facebook_account: "https://www.facebook.com/miguelsilvaface",
				linked_in_account: "http://pt.linkedin.com/pub/pedro-silva/a2/7ab/769",
				location: 'Braga'
			},
			{
				email: 'pmda95<at>hotmail.com',
				password: '123456789',
				first_name: "Duarte",
				last_name: "Araújo",
				sex: UserSex::UNDEFINED,
				username: I18n.transliterate('Duarte Araújo').downcase.gsub(' ', ''),
				avatar: File.open("#{Rails.root}/public/img/staff/daraujo.jpg"),
				is_univ_student: true,
				is_student_at_minho_univ: true,
				minho_univ_student_id: 'a123456',
				is_inf_eng_student_at_minho_univ: true,
				is_cesium_associate: true,
				cesium_associate_number: 0,
				is_organizer: true,
				organizer_role: "Membro",
				activities: [],
				editions: [editions[0]],
				twitter_account: "https://twitter.com/PMDAraujo",
				github_account: "https://github.com/PMDA",
				facebook_account: "https://www.facebook.com/Duarte.Araujo1",
				linked_in_account: "",
				location: 'Braga'
			}
		]
	end
end
