var speakers =
        // slide 01#
        [
            {pic:'img/speakers/hpinto.jpg', name:'Hélder Pinto', position:'3D Environment Artist' , enterprise:[{name:'Blizzard', enterpriseUrl:'http://eu.blizzard.com/'}], web:'http://www.helderpinto.com/' , twitter:'https://twitter.com/HelderHP', github:'',
                about:'Começou carreira profissional na indústria dos vídeo jogos em terras Lusitanas na Seed Studios, no ano de 2007, onde trabalhou no jogo Under Siege Game, partindo depois para a Alemanha, onde ajudou a embelezar os ambientes de Crysis 2 e 3 antes de finalmente começar na Blizzard na Califórnia onde de momento trabalha no jogo Overwatch.'},
            {pic:'img/speakers/lfonseca.jpg', name:'Luís Fonseca', position:'Lead Interactive Developer' , enterprise:[{name:'X-Team',enterpriseUrl:'http://x-team.com/'}], web:'http://luispedrofonseca.com/' , twitter:'https://twitter.com/lpfonseca', github:'',
                about:'Com mais de uma década de experiência num leque muito variado de tecnologias, desde Unity a Objective-C passando pelo Javascript e Flash, focou-se fortemente, nos últimos anos, em desenvolvimento de jogos e aplicações mobile. Faz parte da X-Team desde 2008 onde trabalha, em parceria, para empresas como RIOT Games, Dreamworks, FOX Broadcasting, Microsoft, etc., criando projectos que alcançam todos os dias milhões de utilizadores.'},
            {pic:'img/speakers/fmendes.jpg', name:'Francisco Mendes', position:'Entrepreneur & Creator' , enterprise:[{name:'Bee Very Creative',  enterpriseUrl:'https://beeverycreative.com/'}], web:'https://www.beeverycreative.com' , twitter:'https://twitter.com/fmendes75/', github:'',
                about:'Empreendedor apaixonado por tecnologia. Licenciado em Engenharia Electrónica e Telecomunicações e pós-graduado em Engenharia de Automação Industrial, ambos pela Universidade de Aveiro, começou a sua carreira profissional como Engenheiro de I&D e posteriormente como diretor de Hardware. No final de 2010, juntou-se a Jorge Pinto e fundaram a bitBOX Electronic Systems na incubadora de empresas da Universidade de Aveiro, que mais tarde tornou-se na BEEVERYCREATIVE, a empresa que criou a primeira impressora 3D portuguesa.'},
            {pic:'img/speakers/rmachado.jpg', name:'Roberto Machado', position:'CEO' , enterprise:[{name:'Group Buddies',  enterpriseUrl:'https://groupbuddies.com/'}], web:'http://groupbuddies.com/' , twitter:'https://twitter.com/rmdgb', github:'https://github.com/rmdmachado',
                about:'Engenheiro Informático de formação pela Universidade do Minho, tem muita experiência em Gestão e Empreendedorismo. Sempre teve especial interesse na criação de novos projectos. Atualmente é CEO da Group Buddies, uma empresa que desenvolve produtos web e mobile, onde tem a oportunidade de gerir um grupo de profissionais apaixonados pelo mundo da Web.'},
            {pic:'img/speakers/mpalhas.jpg', name:'Miguel Palhas', position:'Developer & SysAdmin' , enterprise:[{ name:'Group Buddies',  enterpriseUrl:'https://groupbuddies.com/'}], web:'' , twitter:'https://twitter.com/Naps62', github:'https://github.com/naps62',
                about:'Formado na Universidade do Minho, mantém ainda a sua paixão por alta performance e Game Development. Juntou-se à Group Buddies para poder continuar a experimentar novas tecnologias e trabalhar em projectos aliciantes. Fez parte da organização da primeira RubyConf Portugal e é um contribuidor extremamente activo para a comunidade de Open Source'},

            {pic:'img/speakers/gpoca.png', name:'Gabriel Poça', position:'Developer' , enterprise:[{name:'Group Buddies',  enterpriseUrl:'https://groupbuddies.com/'}], web:'http://gabrielpoca.com/' , twitter:'https://twitter.com/gabrielgpoca', github:'https://github.com/gabrielpoca',
                about:'Ninguém sabe realmente muito sobre ele mas diz-se que estudou na Universidade do Minho, que é viciado em software e que o seu primeiro tweet ocorreu no dia 13 de Maio de 2010. Consta que faz magia e tem tiques nervosos.'},
            {pic:'img/speakers/jjusto.jpg', name:'João Justo', position:'Developer' , enterprise:[{name:'Group Buddies',  enterpriseUrl:'https://groupbuddies.com/'}], web:'' , twitter:'https://twitter.com/jpjustonunes', github:'https://github.com/joaojusto',
                about:'Estudante de Engenharia de Informática e Computação na U.P. Os seus principais interesses são aplicações móveis e jogos. Recentemente começou a aprender e a ganhar uma especial curiosidade por tecnologias web, tendo entrado para a Group Buddies como apprentice, onde acabou por ganhar um lugar como developer.'},
            {pic:'img/speakers/rdescoffier.png', name:"Rafael D'Escoffier", position:'Developer' , enterprise:[{name:'BloomIdea',enterpriseUrl:'http://bloomidea.com/'}], web:'http://bloomidea.com/' , twitter:'', github:'',
                about:'Estudante de Engenharia Informática na Universidade do Minho e programador na BloomIdea, com foco especial no desenvolvimento de soluções na área das aplicações móveis. Otimista incurável e geek praticante, apaixonado pela tecnologia, natureza e desporto.'},
            {pic:'img/speakers/pvieira.jpg', name:'Paulo Vieira', position:'Developer' , enterprise:[{name:'iMobileMagic',  enterpriseUrl:'http://www.imobilemagic.com/'}], web:'http://www.imobilemagic.com/' , twitter:'https://twitter.com/imobilemagic', github:'',
                about:'Licenciado em Engenharia Informática pela Universidade do Minho, ao longo dos anos, tem estado envolvido na maioria dos projetos e produtos em que a ImobileMagic tem trabalhado, com um foco particular em desenvolvimento de soluções multimédia para vários clientes e no produto de localização e proteção familiar PhoneNear Family Safety. Tem uma experiência já muito vasta em aplicações móveis e, em particular, no ecossistema iOS'},
            {pic:'img/speakers/fcosta.jpg', name:'Francisco Costa', position:'CEO & Founder', enterprise:[{name:'Tricubo,',enterpriseUrl:'https://tricubo.com/'}, {name:'Chique,',enterpriseUrl:'https://chique.pt/'}, {name:'TYMR,',enterpriseUrl:'https://tymr.com/'}, {name:'Venture FC',enterpriseUrl:'https://venturefc.co/'}], web:'https://franciscocosta.com/' , twitter:'https://twitter.com/franciscocosta', github:'',
                about:'Empreendedor de sucesso, licenciado em Engenharia de Sistemas e Informática pela Universidade do Minho. Apaixonado por tecnologia, conta já com mais de uma década de experiência e muito sucesso acumulado em diversas áreas como E-Commerce, Social Shopping e Digital Marketing'},
            {pic:'img/speakers/nfernandes.png', name:'Nuno Fernandes', position:'D&R Director' , enterprise:[{name:'Eurotux',enterpriseUrl:'http://eurotux.com/'}], web:'http://www.eurotux.com' , twitter:'', github:'',
                about:'Licenciado pela Universidade do Minho em Engenharia de Sistemas e Informática é actualmente Diretor de Investigação e Desenvolvimento da Eurotux Informática. Co-Autor do livro Apache Instalação, Configuração Gestão Servidores Web, editado pela FCA, tem sido responsável pela implementação de diversos projectos de infra-estruturas tecnológicas de grande porte.'},
            {pic:'img/speakers/rfiqueira.jpg', name:'Rui Figueira', position:'Developer' , enterprise:[{ name:'Vilt',  enterpriseUrl:'http://www.vilt-group.com'}], web:'http://www.vilt-group.com/en/' , twitter:'', github:'https://github.com/ruifigueira',
                about:'Tem 10 anos de experiência em desenvolvimento web, principalmente em Java. Adora programar e automatizar tarefas aborrecidas (de aborrecido a divertido), e por isso criou o Minium, uma ferramenta para automatização de tarefas e testes web no browser.'},
            {pic:'img/speakers/nhenriques.jpg', name:'Norberto Henriques', position:'Especialista de UX' , enterprise:[{name:'WeDo',enterpriseUrl:'http://www.wedotechnologies.com/pt/'}], web:'https://www.linkedin.com/in/norbertohenriques' , twitter:'', github:'',
                about:'Iniciou a sua atividade durante o seu percurso académico, em projetos de business intelligence com a Oracle e Portugal Telecom. Desde então tem estado ligado à investigação e desenvolvimento em áreas relacionadas com aplicações para a Internet, multimédia e usabilidade. Foi colaborador no Instituto Politécnico de Leiria e foi responsável pela U.C. de Desenho da Interação dos cursos de Engenharia Informática e Informática para a Saúde durante vários anos. Em 2014 integrou a equipa de User Experience da WeDo Technologies, onde é atualmente Especialista de UX.'},
            {pic:'img/speakers/rantunes.jpg', name:'Rui Antunes', position:'Fundador FPV Portugal' , enterprise:[{name:'FPV',enterpriseUrl:'http://fpvportugal.com/'}], web:'http://fpvportugal.com/' , twitter:'', github:'',
                about:'Sempre se interessou com tudo o que estava relacionado com tecnologia e desde alguns anos que tem experiência em aeromodelismo, há cerca de 4 anos começou a ter contacto com multirotores. Actualmente frequenta o 2o ano de Engenharia Informática na Escola Superior de Tecnologia de Castelo Branco.'},

        ];

console.log(JSON.stringify(speakers));